version: "3.5"

services:
  web:
    container_name: django_api
    build:
      context: .
      args:
        - DJANGO_SUPERUSER_USERNAME
        - DJANGO_SUPERUSER_EMAIL
        - DJANGO_SUPERUSER_PASSWORD
    env_file: .env
    restart: always
#    ports:
#      - "8000:80"