# Generated by Django 3.2.7 on 2021-09-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='skills', to='skill.Project'),
        ),
    ]
