# Generated by Django 3.2.7 on 2021-09-03 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 3, 12, 34, 861651, tzinfo=utc), verbose_name='date published'),
        ),
    ]
